apiVersion: apps/v1
kind: Deployment
metadata:
  name: kolmanfreecss-stuff-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kolmanfreecss-stuff
  template:
    metadata:
      labels:
        app: kolmanfreecss-stuff
    spec:
      containers:
        - name: kolmanfreecss-stuff
          image: kolman-freecss/kolman-freecss-stuff
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://kolmanfreecss-stuff-mongo-srv:27017/kolmanfreecss-stuff'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY